Homework 5
ozoncp/ocp-note-api pull request #2
Opened 2021-06-05 07:47 UTC by olezhek28

2021-06-06 18:08 UTC, xmikasax requested changes

2021-06-06 18:08 UTC, xmikasax commented on core/alarmer/alarmer.go
> +					log.Fatalln("failed to send alarm")
Не стоит здесь падать. В твоем случае ты можешь пропустить тик до того, как сделал alarmer.Close и получить панику

2021-06-06 18:08 UTC, xmikasax commented on core/saver/saver_test.go
> +			}()
Что проверяет этот тест? Нет тестов с недостаточным capacity

2021-06-07 07:13 UTC, olezhek28 commented on core/alarmer/alarmer.go
> +					log.Fatalln("failed to send alarm")
позабыл о том, что за вызовом Fatalln идет вызов Exit.

2021-06-08 08:44 UTC, xmikasax approved these changes

2021-06-08 10:16 UTC, merged